version: "3.7"

services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    # tty: true
    environment:
      MYSQL_ROOT_PASSWORD: "rootpass"
      MYSQL_DATABASE: intelli_base
      TZ: Asia/Tokyo

  # phpmyadmin:
  #   depends_on:
  #     - mysql
  #   image: phpmyadmin/phpmyadmin
  #   environment:
  #     PMA_HOST: mysql
  #   restart: unless-stopped
  #   ports:
  #     - "8080:80"

  app:
    build: ./php-fpm
    volumes:
      - ./htdocs/IntelliBase:/var/www/html
    restart: unless-stopped

  nginx:
    image: nginx:1.21
    volumes:
      - ./htdocs/IntelliBase:/var/www/html
      - ./proxy/conf.d:/etc/nginx/conf.d
      - ./proxy/log:/var/log/nginx
    restart: unless-stopped
    ports:
      - "53002:80"
    depends_on:
      - app

volumes:
  db_data:
